"""
Utility for writing Pulumi outputs to .env file.

Writes infrastructure outputs to a .env file for local development and testing.
"""

from pathlib import Path

import pulumi


def write_outputs_to_env(
    outputs: dict[str, pulumi.Output[str]],
    file_path: str = "infrastructure.env",
) -> None:
    """
    Write Pulumi outputs to a .env file.

    Args:
        outputs: Dictionary of output names to Pulumi Output values.
        file_path: Path to the .env file to write.
    """
    def write_env_file(resolved: dict[str, str]) -> None:
        """Write resolved values to .env file."""
        env_path = Path(file_path)
        lines = [
            "# Auto-generated by Pulumi - DO NOT EDIT",
            "# Re-run 'pulumi up' to regenerate",
            "",
        ]
        for key, value in resolved.items():
            # Convert key to uppercase with underscores
            env_key = key.upper()
            lines.append(f"{env_key}={value}")

        env_path.write_text("\n".join(lines) + "\n")
        pulumi.log.info(f"Outputs written to {file_path}")

    # Gather all outputs and write when resolved
    pulumi.Output.all(**outputs).apply(write_env_file)
